on:
  push:
    branches:
      - 'sonarqube-workflow'
    paths-ignore:
     #- '.github/workflows/**'
  workflow_dispatch:
# workflow_dispatch event will only trigger a workflow run if the workflow file is on the default branch.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

name: Build and Scan
jobs:
  Build:
    name: Build the code and perform static code analysis
    runs-on: ubuntu-latest # Specifies the runner on which the job will run
    environment:
      name: develop
    env:
      SONARQUBE_URL: ${{ vars.SONARQUBE_URL }}
      SONARQUBE_SECRET: ${{ vars.SONARQUBE_SECRET }}

    steps:
    # Cannot reference variables/secrets at Repo level if environment is defined.
        #   - name: Access and output secrets & variables defined at the Repository level.
    #     run: |
    #       echo "Repo URL: ${{ vars.SONARQUBE_URL }}"
    #       echo "Repo Secrets: ${{ secrets.SONARQUBE_SECRET }}"
    
      - name: Access and output Env(develop) specific secrets & variables
        run: |
          echo "Env URL: ${{ env.SONARQUBE_URL }}"
          echo "Env Secrets: ${{ env.SONARQUBE_SECRET }}"


      - name: Checkout source code
        uses: actions/checkout@v3 # Checks out the repository under $GITHUB_WORKSPACE

      - name: Set up JDK 21
        uses: actions/setup-java@v3 # Sets up the specified version of Java
        with:
          java-version: '21' # Specifies the Java version to be set up
          distribution: 'temurin' # Specifies the distribution of JDK
          cache: maven # Caches the Maven dependencies

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5 # Sets up Maven with the specified version
        with:
          maven-version: 3.9.8 # Specifies the Maven version to be set up

      - name: Build with Maven
        run: mvn -U clean install # Runs Maven commands to clean and install the project

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=GH-Action-Java
        env:
          SONAR_TOKEN: ${{ env.SONARQUBE_SECRET }}
          SONAR_HOST_URL: ${{ env.SONARQUBE_URL }}

        
