on:
  push:
    branches:
      - 'sonarqube-workflow'
    paths-ignore:
     #- '.github/workflows/**'
  workflow_dispatch:

name: Build and Scan
jobs:
  Build:
    name: Build the code and perform static code analysis
    runs-on: ubuntu-latest # Specifies the runner on which the job will run
    environment:
      name: develop
    steps:
      - name: Access and output Repo secrets & variables
        run: |
          echo "Repo URL: ${{ vars.SONARQUBE_URL }}"
          echo "Repo Secrets: ${{ secrets.SONARQUBE_SECRET }}"

      - name: Access and output Env() specific secrets & variables
        run: |
          echo "Repo URL: ${{ env.SONARQUBE_URL }}"
          echo "Repo Secrets: ${{ env.SONARQUBE_SECRET }}"


    #   - name: Checkout source code
    #     uses: actions/checkout@v3 # Checks out the repository under $GITHUB_WORKSPACE

    #   - name: Set up JDK 21
    #     uses: actions/setup-java@v3 # Sets up the specified version of Java
    #     with:
    #       java-version: '21' # Specifies the Java version to be set up
    #       distribution: 'temurin' # Specifies the distribution of JDK
    #       cache: maven # Caches the Maven dependencies

    #   - name: Set up Maven
    #     uses: stCarolas/setup-maven@v4.5 # Sets up Maven with the specified version
    #     with:
    #       maven-version: 3.9.8 # Specifies the Maven version to be set up

    #   - name: Build with Maven
    #     run: mvn -U clean install # Runs Maven commands to clean and install the project

        
